<script setup lang="ts">
import { computed, ref } from 'vue';
import { useMessage } from 'naive-ui';
import { RefreshOutline } from '@vicons/ionicons5';
import { api } from '../api';
import type { StatusInfo, UpdateCheckResult } from '../api';

const message = useMessage();
const status = ref<StatusInfo | null>(null);
const updates = ref<UpdateCheckResult[]>([]);
const loading = ref(false);
const checking = ref(false);
const availableUpdates = computed(() => updates.value.filter(result => result.hasUpdate));
async function refresh() { loading.value = true; try { status.value = await api.getStatus(); } catch (error) { message.error(`加载运行状态失败: ${(error as Error).message}`); } finally { loading.value = false; } }
async function checkUpdates() { checking.value = true; try { updates.value = (await api.checkUpdates()).results; } catch (error) { message.error(`检查更新失败: ${(error as Error).message}`); } finally { checking.value = false; } }
refresh();
</script>

<template>
  <div class="app-page status-page"><header class="status-head"><div class="page-heading"><p class="page-kicker">RUNTIME STATUS</p><h1 class="page-title">运行状态</h1><p class="page-summary">以仓库、Agent 和更新可用性为中心的只读健康概览。</p></div><n-button size="small" :loading="loading" @click="refresh"><template #icon><n-icon :component="RefreshOutline" /></template>刷新</n-button></header><n-spin :show="loading"><template v-if="status"><section class="status-metrics"><article><p class="metric-label">CENTRAL SKILLS</p><strong>{{ status.skillCount }}</strong><span>中央仓库 Skill</span></article><article><p class="metric-label">MANAGED</p><strong>{{ status.managedCount }}</strong><span>纳入追踪管理</span></article><article><p class="metric-label">UNMANAGED</p><strong>{{ status.unmanagedCount }}</strong><span>尚待确认来源</span></article><article><p class="metric-label">AGENTS</p><strong>{{ status.installedAgents.length }}</strong><span>已检测 Agent</span></article></section><section class="agent-status surface"><div><p class="meta-label">AGENT COVERAGE</p><h2>Agent 分发密度</h2></div><div class="agent-list"><article v-for="agent in status.agents" :key="agent.agent"><strong>{{ agent.agent }}</strong><div><span><b>{{ agent.managed }}</b> 已管理</span><span><b>{{ agent.unmanaged }}</b> 未管理</span><span><b>{{ agent.total }}</b> 总计</span></div></article><n-empty v-if="status.agents.length === 0" description="尚未检测到 Agent 状态" /></div></section><section class="update-status"><div><p class="meta-label">UPDATE WATCH</p><h2>更新可用性</h2><p>{{ updates.length ? availableUpdates.length ? `${availableUpdates.length} 个 Skill 有可用更新` : '已检查的 Skill 均为最新版本' : '按需检查已关联远程来源的 Skill。' }}</p></div><n-button size="small" :loading="checking" @click="checkUpdates">检查更新</n-button></section><section v-if="updates.length" class="update-list"><article v-for="result in updates" :key="result.name"><strong>{{ result.name }}</strong><span v-if="result.isLocal">本地来源</span><span v-else-if="result.hasUpdate" class="state-warning">{{ result.currentVersion }} → {{ result.remoteVersion }}</span><span v-else class="state-success">已是最新</span></article></section><p class="home-path"><span class="meta-label">CENTRAL REPOSITORY</span><code>{{ status.homeDir }}</code></p></template></n-spin></div>
</template>

<style scoped>
.status-head { display: flex; align-items: flex-end; justify-content: space-between; gap: var(--space-lg); }.status-metrics { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); border: var(--rule); border-radius: var(--radius-lg); overflow: hidden; }.status-metrics article { display: grid; gap: var(--space-2xs); padding: var(--space-lg); border-inline-end: var(--rule); border-block-end: var(--rule); background: var(--color-paper-2); }.status-metrics strong { color: var(--color-ink); font-family: var(--font-display); font-size: var(--text-2xl); letter-spacing: -0.05em; }.status-metrics span { color: var(--color-muted); font-size: var(--text-xs); }.agent-status, .update-status { display: grid; gap: var(--space-lg); padding: var(--space-lg); }.agent-status h2, .update-status h2 { margin: var(--space-xs) 0 0; color: var(--color-ink); font-size: var(--text-lg); letter-spacing: -0.03em; }.agent-list { display: grid; gap: var(--space-xs); }.agent-list article, .update-list article { display: flex; align-items: center; justify-content: space-between; gap: var(--space-sm); padding: var(--space-md); border: var(--rule); border-radius: var(--radius-sm); background: var(--color-paper-2); }.agent-list strong, .update-list strong { color: var(--color-ink); font-size: var(--text-sm); }.agent-list div { display: flex; flex-wrap: wrap; gap: var(--space-sm); color: var(--color-muted); font-size: var(--text-xs); }.agent-list b { color: var(--color-ink); font-family: var(--font-mono); }.update-status { grid-template-columns: minmax(0, 1fr) auto; align-items: end; background: var(--color-graphite); color: var(--color-graphite-ink); }.update-status h2 { color: inherit; }.update-status p:not(.meta-label) { margin: var(--space-xs) 0 0; color: var(--color-graphite-ink); font-size: var(--text-sm); }.update-status .meta-label { color: var(--color-accent); }.update-list { display: grid; gap: var(--space-xs); }.update-list span { font-family: var(--font-mono); font-size: var(--text-xs); }.home-path { display: grid; gap: var(--space-xs); padding: var(--space-md); margin: 0; border-block-start: var(--rule); }.home-path code { overflow-wrap: anywhere; color: var(--color-muted); font-family: var(--font-mono); font-size: 0.625rem; } @media (min-width: 40rem) { .status-metrics { grid-template-columns: repeat(4, minmax(0, 1fr)); }.status-metrics article { border-block-end: 0; }.status-metrics article:last-child { border-inline-end: 0; } } @media (max-width: 39.99rem) { .status-head { flex-direction: column; align-items: stretch; }.update-status { grid-template-columns: 1fr; align-items: start; } }
</style>
