<script setup lang="ts">
import { computed, ref } from 'vue';
import { RefreshOutline } from '@vicons/ionicons5';
import { useToast } from '../composables/useToast';
import { api } from '../api';
import AgentIcon from '../components/agent-icon.vue';
import PageHeader from '../components/ui/PageHeader.vue';
import UiButton from '../components/ui/UiButton.vue';
import UiSpin from '../components/ui/UiSpin.vue';
import UiIcon from '../components/ui/UiIcon.vue';
import type { StatusInfo, UpdateCheckResult } from '../api';

const message = useToast();
const status = ref<StatusInfo | null>(null);
const updates = ref<UpdateCheckResult[]>([]);
const loading = ref(false);
const checking = ref(false);
const availableUpdates = computed(() => updates.value.filter(result => result.hasUpdate));
const maxTotal = computed(() => Math.max(1, ...(status.value?.agents.map(agent => agent.total) ?? [1])));
async function refresh() { loading.value = true; try { status.value = await api.getStatus(); } catch (error) { message.error(`加载 Agent 状态失败: ${(error as Error).message}`); } finally { loading.value = false; } }
async function checkUpdates() { checking.value = true; try { updates.value = (await api.checkUpdates()).results; } catch (error) { message.error(`检查更新失败: ${(error as Error).message}`); } finally { checking.value = false; } }
refresh();
</script>

<template>
  <div class="agents-workspace">
    <PageHeader eyebrow="Agent 注册表" title="Agent 状态" summary="查看可用目录、Skill 覆盖和运行状态。"><template #actions><UiButton size="sm" :loading="loading" @click="refresh"><template #icon><UiIcon :component="RefreshOutline" size="16" /></template>刷新</UiButton></template></PageHeader>
    <UiSpin :show="loading"><template v-if="status">
      <section class="registry-summary"><div class="summary-health"><i /><span><b>本地工作区运行正常</b><small>{{ status.installedAgents.length }} 个 Agent 已检测</small></span></div><dl><div><dt>技能总数</dt><dd>{{ status.skillCount }}</dd></div><div><dt>已纳管</dt><dd>{{ status.managedCount }}</dd></div><div><dt>未关联</dt><dd>{{ status.unmanagedCount }}</dd></div><div><dt>可更新</dt><dd>{{ availableUpdates.length || '—' }}</dd></div></dl></section>
      <section class="agent-registry"><div class="registry-heading"><div><p>已安装 Agent</p><h2>分发目标</h2></div><span>{{ status.agents.length }} 个已登记</span></div><div class="agent-cards"><article v-for="agent in status.agents" :key="agent.agent"><header><AgentIcon :agent-id="agent.agent" :agent-name="agent.agent" :size="36" /><div class="agent-identity"><b>{{ agent.agent }}</b><span>{{ status.installedAgents.includes(agent.agent) ? '可用' : '已检测' }}</span></div><i /></header><div class="agent-stat"><strong>{{ agent.total }}</strong><span>已安装 Skill</span></div><div class="coverage-bar"><i :style="{ width: `${agent.total / maxTotal * 100}%` }" /></div><footer><span><i />{{ agent.managed }} 个已纳管</span><span v-if="agent.unmanaged" class="warning">{{ agent.unmanaged }} 个未纳管</span><span v-else>状态正常</span></footer></article></div></section>
      <section class="update-watch"><div><p>更新监控</p><h2>{{ updates.length ? availableUpdates.length ? `${availableUpdates.length} 个 Skill 可更新` : '当前均为最新版本' : '尚未检查远程更新' }}</h2><span>只检查已关联远程来源的 Skill，不会自动写入。</span></div><button type="button" :disabled="checking" @click="checkUpdates">{{ checking ? '检查中…' : '检查更新' }}</button></section>
      <section v-if="updates.length" class="update-results"><article v-for="result in updates" :key="result.name"><b>{{ result.name }}</b><span v-if="result.isLocal">本地来源</span><span v-else-if="result.hasUpdate" class="warning">{{ result.currentVersion }} → {{ result.remoteVersion }}</span><span v-else class="success">已是最新</span></article></section>
      <footer class="repository-path"><span>中央仓库</span><code>{{ status.homeDir }}</code></footer>
    </template></UiSpin>
  </div>
</template>

<style scoped>
.agents-workspace { width: 100%; max-width: 96rem; margin: 0 auto; padding: 1.25rem 1.5rem 3rem; }.agents-workspace > header { display: flex; align-items: end; justify-content: space-between; gap: 1rem; }.agents-workspace > header p,.registry-heading p,.update-watch p { margin: 0; color: var(--color-faint); font-family: var(--font-mono); font-size: .75rem; font-weight: 650; letter-spacing: .1em; }.agents-workspace > header h1 { margin: .28rem 0 0; color: var(--color-ink); font-size: 1.45rem; letter-spacing: -.045em; }.agents-workspace > header span { display: block; margin-top: .3rem; color: var(--color-muted); font-size: .75rem; }.agents-workspace > header button,.update-watch button { display: flex; height: 1.95rem; align-items: center; gap: .35rem; border: 1px solid var(--color-rule); border-radius: var(--radius-sm); background: var(--color-paper); padding: 0 .62rem; color: var(--color-ink-2); font-size: .75rem; box-shadow: var(--shadow-xs); }
.registry-summary { display: flex; align-items: center; justify-content: space-between; gap: 1rem; margin-top: 1.1rem; border: 1px solid var(--color-rule); border-radius: var(--radius-lg); background: var(--color-paper); padding: .65rem .8rem; box-shadow: var(--shadow-xs); }.summary-health { display: flex; align-items: center; gap: .65rem; }.summary-health > i { width: .48rem; height: .48rem; border-radius: 999px; background: var(--color-success); box-shadow: 0 0 0 4px var(--color-success-soft); }.summary-health b,.summary-health small { display: block; }.summary-health b { color: var(--color-ink); font-size: .75rem; }.summary-health small { margin-top: .07rem; color: var(--color-muted); font-size: .75rem; }.registry-summary dl { display: flex; margin: 0; }.registry-summary dl > div { min-width: 5rem; border-left: 1px solid var(--color-rule); padding: .05rem .8rem; }.registry-summary dt { color: var(--color-faint); font-family: var(--font-mono); font-size: .75rem; text-transform: uppercase; }.registry-summary dd { margin: .05rem 0 0; color: var(--color-ink); font-size: .78rem; font-weight: 650; }
.agent-registry { margin-top: 1rem; }.registry-heading { display: flex; align-items: end; justify-content: space-between; margin-bottom: .55rem; }.registry-heading h2,.update-watch h2 { margin: .25rem 0 0; color: var(--color-ink); font-size: .84rem; letter-spacing: -.025em; }.registry-heading > span { color: var(--color-faint); font-family: var(--font-mono); font-size: .75rem; }.agent-cards { display: grid; grid-template-columns: repeat(auto-fill,minmax(14rem,1fr)); gap: .55rem; }.agent-cards > article { display: grid; gap: .75rem; border: 1px solid var(--color-rule); border-radius: var(--radius-lg); background: var(--color-paper); padding: .75rem; box-shadow: var(--shadow-xs); }.agent-cards > article:hover { border-color: var(--color-rule-strong); box-shadow: var(--shadow-sm); }.agent-cards header { display: grid; grid-template-columns: auto minmax(0,1fr) auto; align-items: center; gap: .55rem; }.agent-identity b,.agent-identity span { display: block; }.agent-identity b { color: var(--color-ink); font-size: .75rem; }.agent-identity span { margin-top: .06rem; color: var(--color-success); font-family: var(--font-mono); font-size: .75rem; }.agent-cards header > i { width: .4rem; height: .4rem; border-radius: 999px; background: var(--color-success); box-shadow: 0 0 0 3px var(--color-success-soft); }.agent-stat { display: flex; align-items: baseline; gap: .4rem; }.agent-stat strong { color: var(--color-ink); font-size: 1.25rem; letter-spacing: -.05em; }.agent-stat span { color: var(--color-muted); font-size: .75rem; }.coverage-bar { height: .25rem; overflow: hidden; border-radius: 999px; background: var(--color-paper-3); }.coverage-bar i { display: block; min-width: .2rem; height: 100%; border-radius: inherit; background: var(--color-accent); }.agent-cards footer { display: flex; justify-content: space-between; padding-top: .55rem; border-top: 1px solid var(--color-rule); color: var(--color-faint); font-family: var(--font-mono); font-size: .75rem; }.agent-cards footer span { display: flex; align-items: center; gap: .3rem; }.agent-cards footer span i { width: .3rem; height: .3rem; border-radius: 999px; background: var(--color-success); }.warning { color: var(--color-warning) !important; }.success { color: var(--color-success) !important; }
.update-watch { display: flex; align-items: center; justify-content: space-between; gap: 1rem; margin-top: 1rem; border: 1px solid var(--color-rule); border-radius: var(--radius-lg); background: var(--color-paper); padding: .75rem .85rem; box-shadow: var(--shadow-xs); }.update-watch > div > span { display: block; margin-top: .15rem; color: var(--color-muted); font-size: .75rem; }.update-results { display: grid; gap: .2rem; margin-top: .4rem; }.update-results article { display: flex; justify-content: space-between; border: 1px solid var(--color-rule); border-radius: var(--radius-sm); background: var(--color-paper); padding: .48rem .6rem; }.update-results b { color: var(--color-ink); font-size: .75rem; }.update-results span { color: var(--color-faint); font-family: var(--font-mono); font-size: .75rem; }.repository-path { display: flex; align-items: center; gap: .7rem; margin-top: .8rem; color: var(--color-faint); font-family: var(--font-mono); font-size: .75rem; text-transform: uppercase; }.repository-path code { overflow-wrap: anywhere; color: var(--color-muted); font-size: .75rem; text-transform: none; }
@media (max-width: 720px) { .agents-workspace { padding: 1rem .9rem 2.5rem; }.registry-summary { align-items: stretch; flex-direction: column; }.registry-summary dl { display: grid; grid-template-columns: repeat(4,1fr); }.registry-summary dl > div { min-width: 0; padding: .35rem .5rem; }.update-watch { align-items: stretch; flex-direction: column; } }

.agents-workspace { max-width: var(--content-max-width); padding: 2rem 2.25rem 4rem; }
.registry-summary { margin-top: 1.5rem; padding: .9rem 1rem; }
.summary-health b { font-size: .78rem; }.summary-health small { font-size: .75rem; }
.registry-summary dl>div { min-width: 6rem; padding: .15rem 1rem; }.registry-summary dt { font-size: .75rem; }.registry-summary dd { font-size: 1rem; }
.agent-registry { margin-top: 1.35rem; }.registry-heading { margin-bottom: .75rem; }.registry-heading h2,.update-watch h2 { font-size: 1rem; }
.agent-cards { grid-template-columns: repeat(auto-fill,minmax(16rem,1fr)); gap: 1rem; }.agent-cards>article { gap: 1rem; padding: 1rem; }
.agent-stat span,.update-watch>div>span { font-size: .75rem; }
.update-watch { margin-top: 1.35rem; padding: 1rem 1.1rem; }
.agents-workspace > header p,.registry-heading p,.update-watch p { font-size:.75rem; }.agents-workspace > header h1 { font-size:2rem; }.agents-workspace > header span { font-size:.95rem; }.agents-workspace > header button,.update-watch button { height:2.4rem;padding:0 .8rem;font-size:.85rem; }
.registry-summary { padding:1.1rem 1.2rem; }.summary-health b { font-size:.92rem; }.summary-health small { margin-top:.18rem;font-size:.8rem; }.registry-summary dt { font-size: .75rem; }.registry-summary dd { margin-top:.12rem;font-size:1.15rem; }
.registry-heading h2,.update-watch h2 { font-size:1.15rem; }.registry-heading>span { font-size:.75rem; }.agent-cards>article { padding:1.15rem; }.agent-identity b { font-size:.92rem; }.agent-identity span { font-size: .75rem; }.agent-stat span,.update-watch>div>span { font-size:.8rem; }.agent-cards footer { font-size: .75rem; }.update-results b { font-size:.85rem; }.update-results span,.repository-path,.repository-path code { font-size: .75rem; }
</style>
